### PR TITLE
Support JSON response body

### PR DESCRIPTION
**Pull request by ddrozdov**
This implements issue #2
Store JSON response body in jsonBody field; Transform dot notation to nested JSON

### CODE REVIEW

**Comment by ddrozdov** [comment]
That's my first experience in Go so it is probably not the best solution, but still it works :)

**Comment by christiangalsterer** [comment]
Finally I had some time to look into it. 
What I have in mind is to use only one fields and depending on the type of the response of the HTTP call this is then either a simple string of a json structure. 

If the HTTP response can be parsed as a json object then it will be returned as a json structure. Here I plan to use the mode parameter is in your PR. If the HTTP response cannot be parsed as a structure then the response as returned unchanged as a string.

What do you think?

**Comment by ddrozdov** [comment]
Thought about it, but this would make it impossible to use the same index name for both json and non-json responses because the `body` field type in Elasticsearch can't be a `string` and a `group` at the same time.

**Comment by christiangalsterer** [comment]
Valid point, will rethink it again.

**Comment by ddrozdov** [comment]
Any news here?

**Comment by christiangalsterer** [comment]
I was busy with some activities in the last weeks. I will look into it the next days but most likely the PR will  be merged unchanged or only smaller internal changes and keeping the approach using a dedicated field.

**Comment by christiangalsterer** [comment]
I merged your PR unchanged and a release 1.1.0 is available. Thanks very much for your contribution again.

**Comment by ddrozdov** [comment]
:thumbsup:

**Pull request merged**
